# Generated by Django 4.2.3 on 2024-05-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Client'), (2, 'Operator'), (3, 'Supervisor'), (4, 'Admin'), (10, 'Superadmin')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profileverification',
            name='type_verification',
            field=models.SmallIntegerField(choices=[(1, 'Verificación de teléfono'), (2, 'Verificación de correo electrónico'), (3, 'Recuperar contraseña con teléfono'), (4, 'Recuperar contraseña con correo electrónico'), (5, 'Cambiar el numero teléfono'), (6, 'Verificación doble factor de autentificación')], default=1),
        ),
    ]
