# Generated by Django 4.2.3 on 2024-05-30 12:51

import common.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstratoApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('volcan_issuer_id', models.CharField(max_length=100)),
                ('url_estrato', models.URLField(blank=True, null=True)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('header_request', models.CharField(default='X-Api-Key', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='api_keys', to='control.company')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, common.models.NameStrMixin),
        ),
    ]
