# Generated by Django 4.1.2 on 2023-04-25 16:19

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('slug', models.SlugField(max_length=45, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, common.models.NameStrMixin),
        ),
    ]
