# Generated by Django 4.2.3 on 2023-10-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='header_webhook',
            field=models.CharField(default='Authorization', max_length=20),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='key_webhook',
            field=models.TextField(blank=True, null=True),
        ),
    ]
