# Generated by Django 4.2.3 on 2024-05-29 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
        ('webhook', '0002_webhook_header_webhook_alter_webhook_key_webhook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhook',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='webhook',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='webhooks', to='control.company'),
        ),
    ]
