# Generated by Django 4.2.11 on 2024-09-19 15:57

import common.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corresponsalia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('branch', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('user_paycard', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('authorization', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('params', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='corresponsalias', to='control.company')),
            ],
            options={
                'ordering': ['country', 'city', 'branch'],
            },
            bases=(models.Model, common.models.NameStrMixin),
        ),
    ]
