# Generated by Django 4.2.11 on 2024-09-25 16:05

import common.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('thalesapi', '0009_merge_20240605_1803'),
        ('control', '0002_currency'),
        ('corresponsalia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionCorresponsalia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(max_length=16)),
                ('movement_code', models.CharField(blank=True, max_length=4, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('processed', 'Procesado'), ('rejected', 'Rechazado'), ('error', 'Error'), ('returned', 'Reverso'), ('error_returned', 'Error en reverso')], default='active', max_length=20)),
                ('card_bin_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='thalesapi.cardbinconfig')),
                ('corresponsalia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='corresponsalia.corresponsalia')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='control.currency')),
            ],
            options={
                'ordering': ['created_at', 'card_number', 'currency'],
            },
            bases=(models.Model, common.models.NameStrMixin),
        ),
    ]
