# Generated by Django 4.2.11 on 2024-09-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corresponsalia', '0002_transaccioncorresponsalia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corresponsalia',
            old_name='authorization',
            new_name='description',
        ),
        migrations.AddField(
            model_name='corresponsalia',
            name='access_token_paycard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corresponsalia',
            name='pass_paycard',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaccioncorresponsalia',
            name='authorization',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
