# Generated by Django 4.2.11 on 2024-10-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corresponsalia', '0003_rename_authorization_corresponsalia_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccioncorresponsalia',
            name='movement_code_reverse',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
