# Generated by Django 4.2.11 on 2024-09-11 20:33

import common.models
from django.db import migrations, models
import django.db.models.deletion
import reports.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0001_initial'),
        ('users', '0002_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('logs', 'Logs')], default='logs', max_length=50)),
                ('initial_date', models.DateTimeField(blank=True, null=True)),
                ('final_date', models.DateTimeField(blank=True, null=True)),
                ('time_zone', models.CharField(default='America/Mexico_City', max_length=50)),
                ('report', models.FileField(blank=True, null=True, upload_to=reports.models.report_directory_path)),
                ('params', models.JSONField(default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports', to='control.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.profile')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, common.models.NameStrMixin),
        ),
    ]
