# Generated by Django 4.2.3 on 2023-08-28 19:06

import common.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issuer_id', models.CharField(help_text='Thales Issuer ID', max_length=100, verbose_name='Issuer ID')),
                ('card_id', models.CharField(help_text='Generated by AZ7', max_length=100, verbose_name='Card ID')),
                ('consumer_id', models.CharField(help_text='Generated by AZ7', max_length=100, verbose_name='Consumer ID')),
                ('card_type', models.CharField(choices=[('prepaid', 'Prepago'), ('credit', 'Credito'), ('other', 'Otro')], default='prepaid', max_length=10)),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=(models.Model, common.models.NameStrMixin, common.models.ModelDiffMixin),
        ),
    ]
