# Generated by Django 4.2.3 on 2023-08-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thalesapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetail',
            name='card_bin',
            field=models.CharField(blank=True, help_text='Thales Card BIN', max_length=8, null=True, verbose_name='Card BIN'),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='card_id',
            field=models.CharField(help_text='Generated by AZ7', max_length=48, verbose_name='Card ID'),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='consumer_id',
            field=models.CharField(help_text='Generated by AZ7', max_length=64, verbose_name='Consumer ID'),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='issuer_id',
            field=models.CharField(help_text='Thales Issuer ID', max_length=10, verbose_name='Issuer ID'),
        ),
    ]
