# Generated by Django 4.2.3 on 2023-10-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thalesapi', '0003_carddetail_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISOCountry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=4)),
                ('country_name', models.CharField(max_length=100)),
                ('alfa2', models.CharField(max_length=2)),
                ('alfa3', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ('country_name',),
            },
        ),
    ]
