# Generated by Django 4.2.3 on 2023-12-09 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('thalesapi', '0004_isocountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBinConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_bin', models.CharField(blank=True, help_text='Thales Card BIN', max_length=8, null=True, unique=True, verbose_name='Card BIN')),
                ('issuer_id', models.CharField(help_text='Thales Issuer ID', max_length=10, verbose_name='Issuer ID')),
                ('card_type', models.CharField(choices=[('prepaid', 'Prepago'), ('credit', 'Credito'), ('other', 'Otro')], default='prepaid', help_text='Thales Card Type', max_length=10, verbose_name='Card Type')),
                ('card_product_id', models.CharField(help_text='Thales Card Product ID', max_length=32, verbose_name='Card Product ID')),
                ('emisor', models.CharField(default='CMF', help_text='Volcan Emisor ID', max_length=3, verbose_name='Volcan Emisor ID')),
            ],
            options={
                'ordering': ('card_bin',),
            },
        ),
        migrations.AddField(
            model_name='carddetail',
            name='emisor',
            field=models.CharField(blank=True, default='CMF', help_text='Volcan Emisor ID', max_length=3, null=True, verbose_name='Volcan Emisor ID'),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='card_type',
            field=models.CharField(choices=[('prepaid', 'Prepago'), ('credit', 'Credito'), ('other', 'Otro')], default='prepaid', help_text='Thales Card Type', max_length=10, verbose_name='Card Type'),
        ),
    ]
