# Generated by Django 4.2.3 on 2023-12-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thalesapi', '0005_cardbinconfig_carddetail_emisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardbinconfig',
            name='card_product_id',
            field=models.CharField(help_text='Thales Card Product ID', max_length=100, verbose_name='Card Product ID'),
        ),
    ]
