# Generated by Django 4.2.3 on 2024-06-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thalesapi', '0007_client_carddetail_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document_identification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
