# Generated by Django 4.2.3 on 2024-06-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thalesapi', '0008_alter_client_document_identification'),
        ('thalesapi', '0008_cardbinconfig_company_carddetail_company'),
    ]

    operations = [
    ]
