# Generated by Django 4.2.11 on 2024-09-25 15:39

import common.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=45)),
                ('abr_code', models.CharField(max_length=3)),
                ('number_code', models.CharField(max_length=3)),
                ('decimals', models.SmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['abr_code'],
            },
            bases=(models.Model, common.models.NameStrMixin),
        ),
    ]
